### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by alimanfoo**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by alimanfoo** [comment]
@conda-forge-admin, please rerender

**Comment by alimanfoo** [comment]
I'm trying to get the tests run but excluding two specific tests that require `tabix`, which is an optional dependency and not available in conda-forge. A better future strategy will be to detect presence/absence of tabix within the test code and to skip relevant tests if tabix is not available, however for now I'm just trying to find a way of getting pytest to not run those tests, which is proving difficult.

The two tests I'm trying to not run are:

* allel/test/io/test_gff_read.py::test_gff3_to_dataframe_region
* allel/test/model/ndarray/test_tables.py::FeatureTableTests::test_from_gff3_region

The problem is that because we have to use --pyargs, then I can't get the --deselect option to work (have tried various syntaxes).

In the latest commit (a437457) I used -k with a 'not ...' expression, which works on linux and osx, but for some reason fails on windows with this:

```
ERROR: file or package not found: test_gff3_to_dataframe_region (missing __init__.py?)
```

Strange that pytest should behave differently on these different platforms. 

@conda-forge/core sorry to bother you, any help appreciated.

**Comment by CJ-Wright** [comment]
You could package the missing dep our remove the running of the test suite.

**Comment by alimanfoo** [comment]
Ok, thanks. Packaging tabix is a bit complicated, currently downstream in
bioconda. Could skip all tests, but would be nice to run them.

If no-one knows how to get pytest to skip specific tests when run with
--pyargs then maybe I'll add some skip logic in the source code and make a
new release.

**Comment by alimanfoo** [comment]
I've cut down the tests for now, should be enough. Will merge this if CI passes.

**Pull request merged**
